services:
  - type: web
    name: mortalidad-colombia-2019
    env: python
    pythonVersion: 3.12.6
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: DATA_DIR
        value: data
      - key: MORTALITY_FILE
        value: NoFetal2019.xlsx
      - key: CAUSES_FILE
        value: CodigosDeMuerte.xlsx
      - key: DIVIPOLA_FILE
        value: Divipola.xlsx
      - key: GEOJSON_FILE
        value: colombia_departamentos.geojson
      - key: HOMICIDE_CODES
        value: X93,X94,X95,Y09
